apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: tekton-config
  namespace: tekton
spec:
  profile: 'all'
  targetNamespace: tekton
  pruner:
    disable: true
    resources:
      - pipelinerun
      - taskrun
    keep: 100
    schedule: "0 8 * * *"
  pipeline:
    enable-tekton-oci-bundles: true
  dashboard:
    readonly: false

