apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  namespace: ${TEKTON_NS}
spec:
  profile: ${TEKTON_PROFILE}
  targetNamespace: ${TEKTON_NS}
  pruner:
    resources:
      - pipelinerun
      - taskrun
    keep: 100
    schedule: "0 8 * * *"
  pipeline:
    enable-tekton-oci-bundles: true
  dashboard:
    readonly: false
