apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-funnel

resources:
  - namespace.yaml
  - quota.yaml
  - limitrange.yaml
  - deploy.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: nginx-pages
    files:
      - pages/index.html
      - pages/about.html
      - pages/status.html

generatorOptions:
  disableNameSuffixHash: true
